// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Ajout2itemgrillesFOetFOSAMRC : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ajout2itemgrillesFOetFOSAMRC));
        
        string IMigrationMetadata.Id
        {
            get { return "202102160834483_Ajout 2 item grilles FO et FOSAMRC"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
